### PR TITLE
add focal

### PR DESCRIPTION
**Pull request by BaronMsk**

### CODE REVIEW

**Comment by FlorentPoinsaut** [comment]
Thank you for your contribution.
Could you add some tests please?

**Comment by BaronMsk** [comment]
@FlorentPoinsaut Hi, done

**Comment by dandunckelman** [comment]
Anything holding this up from being merged?

**Comment by zilchms** [comment]
Thanks for your contribution, ubuntu 20.04 (focal) was added in #53, so I will be closing this :)

**Pull request closed without merging**
