### PR TITLE
drop EOL OSes; add amazon 2023

### PR DESCRIPTION
**Pull request by zilchms**
Needed to have any chance of fixing #24

### CODE REVIEW

**Comment by bastelfreak** [comment]
Can you please split the different OSes into multiple PRs, so each dropped OS is listed in the changelog?

**Comment by zilchms** [comment]
sure can do, "one version one pr" or "one os one pr" ?

**Comment by bastelfreak** [comment]
One OS per PR is fine

**Comment by zilchms** [comment]
done in #36 #37 #38 #39 #40 #41 #42

**Pull request closed without merging**
